### ISSUE TITLE
Example Request

### ISSUE THREAD

**Issue by eokgnah** [carlosperezc/nspanel#1]
Hello Carlos,

thanks for the work, this is exactly what i need.
But i still don't understand it.

So please can you give me an example?

1. i have made my own hmi in NextionEditor
2. there is a Page "0" named "main"
3. on this page is a text field (type 116) with id "3" and objname "zeit"

mosquitto_pub -h mqtt.server -u *** -P *** -t "NSPanel/Panel01/cmnd/Nextion" -m "0.3.txt=test"
or
mosquitto_pub -h mqtt.server -u *** -P *** -t "NSPanel/Panel01/cmnd/Nextion" -m "main.zeit.txt=test"
or
mosquitto_pub -h mqtt.server -u *** -P *** -t "NSPanel/Panel01/cmnd/Nextion" -m "0.3.txt=\"test\""
or
mosquitto_pub -h mqtt.server -u *** -P *** -t "NSPanel/Panel01/cmnd/Nextion" -m "main.zeit.txt=\"test\""

i always get: RESULT "Command:Unknown"

What am i doing wrong?

**Comment by eokgnah** [comment]
Got it to work.
I had an error in the Berry-Script-Line600

Now i can alter the TXT values over MQTT.

How can i enable/disable an overlay Image?
I think it could work with the dual state button.
But i only can change the text on a bitten, but not the state.

mosquitto_pub -h ** -u ** -P ** -t "NSPanel/Panel01/cmnd/Nextion" -m "main.bt0.txt=\"X\""
= Works

mosquitto_pub -h ** -u ** -P ** -t "NSPanel/Panel01/cmnd/Nextion" -m "main.bt0.val=\"1\""
= does not work

Do you have any Idea how to alter the Image through mqtt?

**Comment by carlosperezc** [comment]
Hi. You can just change the image by another one but should be already uploaded.

The command is something like page.image=thenameofyourimage

Sorry for the late response.

Im not at home but i'll check tonight

Téléchargez Outlook pour iOS<https://aka.ms/o0ukef>
________________________________
De : eokgnah ***@***.***>
Envoyé : Sunday, August 7, 2022 10:53:43 AM
À : carlosperezc/nspanel ***@***.***>
Cc : Subscribed ***@***.***>
Objet : Re: [carlosperezc/nspanel] Example Request (Issue #1)


Got it to work.
I had an error in the Berry-Script-Line600

Now i can alter the TXT values over MQTT.

How can i enable/disable an overlay Image?
I think it could work with the dual state button.
But i only can change the text on a bitten, but not the state.

mosquitto_pub -h ** -u ** -P ** -t "NSPanel/Panel01/cmnd/Nextion" -m "main.bt0.txt="X""
= Works

mosquitto_pub -h ** -u ** -P ** -t "NSPanel/Panel01/cmnd/Nextion" -m "main.bt0.val="1""
= does not work

Do you have any Idea how to alter the Image through mqtt?

**Comment by eokgnah** [comment]
Thanks Carlos,
i'll try with the pictures...
Did it for now with a big red (text) "X" to mark things on the map. 

The rest works fine at the moment.
Found Dimming:
Nextion dim=0  until Nextion dim=100

Will also try to subscribe to topics directly in the berry to set an "X" or not at according points on the map.

Your tft Upload is for US-Displays. I have a EU-Display. So i will adjust it soon as well.
The working script will be available on my github then.
But it takes some polishing until it is ready.

**Comment by eokgnah** [comment]
https://github.com/eokgnah/NSPanel-Nextion/
found a cheat sheet with all possible instructions and made some examples.
thanks for the help to get me there.

**Comment by carlosperezc** [comment]
Hi, 

 

The command is dim (dim=xx where xx is the percent to dim the backlight)

 

There is another command: dims which is also retains the dim setting on reboot.

 

 

Check this page: https://nextion.tech/instruction-set/

 

 

De: eokgnah ***@***.***> 
Enviado el: 8 août 2022 04:27
Para: carlosperezc/nspanel ***@***.***>
CC: Carlos Perez ***@***.***>; Comment ***@***.***>
Asunto: Re: [carlosperezc/nspanel] Example Request (Issue #1)

 

Thanks Carlos,
i'll try with the pictures...
Did it for now with a big red (text) "X" to mark things on the map.

The rest works fine at the moment.
Is there a MQTT message to dim/undim the display?

Your tft Upload is for US-Displays. I have a EU-Display. So i will adjust it soon as well.
The working script will be available on my github then.
But it takes some polishing until it is ready.
