### ISSUE TITLE
How do you Flash with this Version

### ISSUE THREAD

**Issue by OmegaQuest** [carlosperezc/nspanel#2]
I looked at the Code and I cannot figure out how to Flash the TFT file to the Display via Tasmota.  I tried the traditional ways, and none work:

* http://192.168.1.100 is an accessable internal web URL.

FlashNextion http://192.168.1.100/custom.tft
FlashNextion "http://192.168.1.100/custom.tft"
FlashNextion ("192.168.1.100", 80, "/custom.tft", 32768)
FlashNextion("192.168.1.100", 80, "/custom.tft", 32768)

TftDownloader http://192.168.1.100/custom.tft
TftDownloader "http://192.168.1.100/custom.tft"
TftDownloader ("192.168.1.100", 80, "/custom.tft", 32768)
TftDownloader("192.168.1.100", 80, "/custom.tft", 32768)

**Comment by red-centre** [comment]
Sorry if this is obvious, but I had a little trouble getting it to flash, because I hadn't loaded the .be files properly - the Autoexec.bat file as written simply loads another file, which from memory is referred to as NSPanlecustom.be, but the actual berry file is named something different - I think NSPanel.be

**Comment by red-centre** [comment]
Just checked - the Autoexec.be contains this line:
load("nspanelcust.be")
but the .be file in the repo is "nspanel.be"
so if you are just using the files as written, you need to either alter the autoexec.be to be 
load("nspanel.be")
or rename nspanel.be to nspanelcust.be
and make sure both have been uploaded

**Comment by carlosperezc** [comment]
Hi sorry for the late response.

The 192.168.1.100 is just a webserver in your own network where the .be  file you created with the nextion editor resides. you can create a container with apache just to serve the files (that's what i did).
You can rename the .be file as you want (when you save it with the nextion editor)
The autoexec.be in the nspanel indicates which .be file you want to load then the device starts. 
In fact you can upload multiple  .be files on the device but that depends on the size of your .be files.

**Comment by carlosperezc** [comment]
The first time I had to open the device and flash it with a ttl cable

Téléchargez Outlook pour iOS<https://aka.ms/o0ukef>
________________________________
De : OmegaQuest ***@***.***>
Envoyé : Tuesday, August 16, 2022 11:28:08 AM
À : carlosperezc/nspanel ***@***.***>
Cc : Subscribed ***@***.***>
Objet : [carlosperezc/nspanel] How do you Flash with this Version (Issue #2)


I looked at the Code and I cannot figure out how to Flash the TFT file to the Display via Tasmota. I tried the traditional ways, and none work:

  *   http://192.168.1.100 is an accessable internal web URL.

FlashNextion http://192.168.1.100/custom.tft
FlashNextion "http://192.168.1.100/custom.tft"
FlashNextion ("192.168.1.100", 80, "/custom.tft", 32768)
FlashNextion("192.168.1.100", 80, "/custom.tft", 32768)

TftDownloader http://192.168.1.100/custom.tft
TftDownloader "http://192.168.1.100/custom.tft"
TftDownloader ("192.168.1.100", 80, "/custom.tft", 32768)
TftDownloader("192.168.1.100", 80, "/custom.tft", 32768)
