### ISSUE TITLE
Node red

### ISSUE THREAD

**Issue by red-centre** [carlosperezc/nspanel#3]
Hi Carlos,
Firstly, thanks very much for your work on this - I'm really enjoying playing with it.
I'm struggling to figure out how to activate the buttons through node red, would it be possible for you to share a flow with me?
I have managed to get accuweather working to send updates to text boxes, can operate the 2 physical switches, but can't figure out how to trigger state changes in the touch screen "buttons".

**Comment by red-centre** [comment]
Just to update, figured out how to trigger state change on the panel from Node Red, now just trying to figure out how to receive state change into Node Red.

**Comment by carlosperezc** [comment]
Hi, you need just to create a node that subscribes subscribe to the nspanel topic in mqtt and then catch the appropriate message

**Comment by carlosperezc** [comment]
Hello,

You needs just to subscribe to the nspanel topic in mqtt and then catch the appropiate event using nodes.

Hope this works

Téléchargez Outlook pour iOS<https://aka.ms/o0ukef>
________________________________
De : red-centre ***@***.***>
Envoyé : Wednesday, August 17, 2022 7:20:06 PM
À : carlosperezc/nspanel ***@***.***>
Cc : Subscribed ***@***.***>
Objet : Re: [carlosperezc/nspanel] Node red (Issue #3)


Just to update, figured out how to trigger state change on the panel from Node Red, now just trying to figure out how to receive state change into Node Red.
